/** Dynamic import loaders for respondent-facing question components. */
export const QUESTION_LOADERS = {
  single_select:       () => import('./choice/SingleSelectQ.jsx'),
  multi_select:        () => import('./choice/MultiSelectQ.jsx'),
  dropdown:            () => import('./choice/DropdownQ.jsx'),
  open_text:           () => import('./basic/OpenTextQ.jsx'),
  date:                () => import('./basic/DateQ.jsx'),
  matrix:              () => import('./matrix/MatrixQ.jsx'),
  bipolar_matrix:      () => import('./matrix/BipolarMatrixQ.jsx'),
  maxdiff:             () => import('./structured/MaxDiffQ.jsx'),
  card_sort:           () => import('./structured/CardSortQ.jsx'),
  constant_sum:        () => import('./structured/ConstantSumQ.jsx'),
  slider:              () => import('./scale/SliderQ.jsx'),
  nps:                 () => import('./scale/NpsQ.jsx'),
  star_rating:         () => import('./scale/StarRatingQ.jsx'),
  ranking:             () => import('./structured/RankingQ.jsx'),
  textbox_list:        () => import('./structured/TextboxListQ.jsx'),
  semantic_diff:       () => import('./scale/SemanticDiffQ.jsx'),
  cascade:             () => import('./structured/CascadeQ.jsx'),
  image_choice_single: () => import('./choice/ImageChoiceQ.jsx'),
  image_choice_multi:  () => import('./choice/ImageChoiceQ.jsx'),
}
