import { newId } from './id'

export const INITIAL_STATE = {
  survey: {
    id: newId(),
    title: 'Untitled Survey',
    description: '',
    internalName: '',
    surveyCode:   '',
    status:       'draft',
    clientId:     '',
    topicId:      '',
    surveyType:   '',
    coverImage: null,
    showCoverPage: true,
    startButtonText: 'Start Survey',
    companyLogo: null,
    logoPosition: 'left',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    settings: {
      onePerPage: true,
      terminateTitle:   'Thank you for your time.',
      terminateMessage: 'Unfortunately, you do not qualify for this survey.',
      closedTitle:   'This survey is now closed.',
      closedMessage: 'Thank you for your interest. This survey is no longer accepting responses.',
      fingerprinting: {
        enabled: false,
        signals: {
          ip:          true,
          browser:     true,
          os:          true,
          deviceType:  true,
          screen:      true,
          timezone:    true,
          language:    true,
          hardware:    false,
          connection:  false,
          canvas:      true,
          webgl:       false,
          cookies:     false,
          doNotTrack:  false,
          userAgent:   false,
        },
      },
    },
  },
  items: [],
  activeItemId: null,
  focusOptionId: null,
  isDirty: false,
  showPreview: false,
}
