import {
  DEFAULT_DATE_FORMAT,
  DEFAULT_SCREEN_MESSAGES,
  DEFAULT_START_BUTTON_TEXT,
  DEFAULT_SURVEY_TITLE,
} from '@/constants/surveyDefaults'
import { newId } from './id'

export const INITIAL_STATE = {
  survey: {
    id: newId(),
    title: DEFAULT_SURVEY_TITLE,
    description: '',
    internalName: '',
    surveyCode:   '',
    status:       'draft',
    clientId:     '',
    topicId:      '',
    surveyType:   '',
    coverImage: null,
    showCoverPage: true,
    startButtonText: DEFAULT_START_BUTTON_TEXT,
    companyLogo: null,
    logoPosition: 'left',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    settings: {
      onePerPage: true,
      ...DEFAULT_SCREEN_MESSAGES,
      fingerprinting: {
        enabled: false,
        signals: {
          ip:          true,
          browser:     true,
          os:          true,
          deviceType:  true,
          screen:      true,
          timezone:    true,
          language:    true,
          hardware:    false,
          connection:  false,
          canvas:      true,
          webgl:       false,
          cookies:     false,
          doNotTrack:  false,
          userAgent:   false,
        },
      },
    },
  },
  items: [],
  activeItemId: null,
  focusOptionId: null,
  isDirty: false,
  showPreview: false,
}
