/** Auth UI copy — preserves existing casing per surface (heading vs button vs link). */

export const AUTH_COPY = {
  signIn:              'Sign in',
  signOut:             'Sign out',
  createOrgHeading:    'Start your free trial',
  createOrgButton:     'Start free trial',
  createOrgLink:       'Start a free trial',
  createOrgSubtitle:   '14 days free · 5 surveys · 1 seat · no credit card',
  signingIn:           'Signing in…',
  creating:            'Creating…',
}

export const AUTH_VALIDATION = {
  orgRequired:         'Please enter an organization name.',
  nameRequired:        'Please enter your full name.',
  credentialsRequired: 'Please enter an email and password.',
  passwordMinLength:   'Password must be at least 8 characters.',
  passwordsMismatch:   'Passwords do not match.',
  loginRequired:       'Please enter both email and password.',
}

export const AUTH_ERRORS = {
  invalidCredentials:  'Invalid email or password.',
  signupFailed:        'Could not create the organization.',
  emailTakenSignup:    'That email is already registered.',
  emailTakenAdmin:     'That email is already registered.',
  usernameTakenSignup: 'That username is already taken.',
  usernameTakenAdmin:  'That username is already taken.',
  sessionExpired:      'Session expired. Please sign in again.',
  sessionInvalid:      'Session is no longer valid. Please sign in again.',
  forbidden:           'You don\'t have permission to do that.',
}

export const AUTH_TEAM = {
  heading:             'Team activity',
  teamActivity:        'Team activity',
  teamActivityHint:    'Survey activity by employee',
  subtitle:            'Survey activity by employee',
  surveysBuilt:        'Surveys built',
  responses:           'Responses',
  completion:          'Completion',
  lastActive:          'Last active',
  noActivity:          'No activity yet',
  credentialsOnce:     'Copy these credentials now — the password will not be shown again.',
  passwordResetOnce:   'New password set — copy it now. It will not be shown again.',
}

export const AUTH_PROFILE = {
  myAccount:           'My account',
  myProfile:           'My profile',
  myProfileHint:       'Update how you appear across the platform. Password changes require your current password.',
  displayName:         'Display name',
  username:            'Username',
  email:               'Email',
  emailHint:           'Used to sign in. We\'ll send account notifications to this address when available.',
  profilePhoto:        'Profile photo',
  uploadPhoto:         'Upload photo',
  removePhoto:         'Remove',
  photoHint:           'JPEG, PNG, or WebP · max 512 KB',
  changePassword:      'Change password',
  currentPassword:     'Current password',
  newPassword:         'New password',
  confirmPassword:     'Confirm new password',
  saveProfile:         'Save profile',
  profileSaved:        'Profile updated',
  teamMembers:         'Team members',
  teamHint:            'Invite colleagues and manage roles. Seat usage is tied to your subscription.',
  seatsUsed:           'seats used',
  searchMembers:       'Search by name or username…',
  resetPassword:       'Reset password',
  generatePassword:    'Generate secure password',
  adminResetHint:      'Leave blank to keep the current password, or set a new one for this user.',
  noMembers:           'No team members yet.',
  you:                 'You',
}

export const AUTH_BILLING = {
  heading:             'Billing',
  subtitle:            'Subscription and invoices for your organization',
  plan:                'Current plan',
  status:              'Status',
  seats:               'Seats',
  surveys:             'Surveys',
  periodEnd:           'Renews / trial ends',
  freePrice:           'Free',
  trialBanner:         'You are on a free trial. Paid plans are activated by the vendor once billing is connected.',
  changePlan:            'Change plan',
  changePlanSubtitle:    'Upgrade or downgrade your subscription. Changes take effect immediately.',
  currentPlanBadge:      'Current plan',
  upgradePlan:           'Upgrade',
  downgradePlan:         'Downgrade',
  planChangeSuccess:     'Your plan has been updated.',
  planChangeBlocked:     'This plan change is not available yet.',
  confirmDowngradeTitle: 'Confirm plan downgrade',
  confirmDowngradeBody:  'You will lose access to features included in your current plan. This takes effect immediately.',
  invoices:            'Invoices',
  noInvoices:          'No invoices yet.',
  platformHeading:     'Platform console',
  platformSubtitle:    'Manage organizations, subscriptions, and invoices',
  organizations:       'Organizations',
  selectOrg:           'Select an organization to manage its plan and invoices',
  searchOrgs:          'Search organizations…',
  noOrgs:              'No organizations yet',
  platformEmptyHint:   'Customer organizations will appear here once they sign up.',
}
