/** Auth UI copy — preserves existing casing per surface (heading vs button vs link). */

export const AUTH_COPY = {
  signIn:              'Sign in',
  signOut:             'Sign out',
  createOrgHeading:    'Start your free trial',
  createOrgButton:     'Start free trial',
  createAccountButton: 'Create account',
  createOrgLink:       'Start a free trial',
  createOrgSubtitle:   '14 days free · 5 surveys · 1 seat · no credit card',
  signingIn:           'Signing in…',
  creating:            'Creating…',
  loginFormTitle:      'Sign in',
  loginFormSubtitle:   'Use the email and password for your organization account.',
}

/** Left-rail copy on the sign-in screen (matches signup panel tone). */
export const AUTH_LOGIN_WELCOME = {
  eyebrow: 'Welcome back',
  title: 'Your fieldwork survey workspace',
  detail:
    'Sign in to manage surveys, collaborate with your team, and publish links for respondents.',
  highlights: [
    'Advanced logic, piping, and exclusion lists',
    'Team roles and organization settings',
    'Exports and live survey distribution',
  ],
  footerNote: 'Same account you created during signup — one workspace per organization.',
}

export const AUTH_VALIDATION = {
  orgRequired:         'Please enter an organization name.',
  nameRequired:        'Please enter your full name.',
  credentialsRequired: 'Please enter an email and password.',
  passwordMinLength:   'Password must be at least 8 characters.',
  passwordsMismatch:   'Passwords do not match.',
  loginRequired:       'Please enter both email and password.',
}

export const AUTH_ERRORS = {
  invalidCredentials:  'Invalid email or password.',
  signupFailed:        'Could not create the organization.',
  emailTakenSignup:    'That email is already registered.',
  emailTakenAdmin:     'That email is already registered.',
  usernameTakenSignup: 'That username is already taken.',
  usernameTakenAdmin:  'That username is already taken.',
  sessionExpired:      'Session expired. Please sign in again.',
  sessionInvalid:      'Session is no longer valid. Please sign in again.',
  forbidden:           'You don\'t have permission to do that.',
}

/** Emailed one-time-link flows: forgot / reset password, accept invite, verify email. */
export const AUTH_ACCOUNT = {
  forgotLink:          'Forgot password?',
  forgotTitle:         'Reset your password',
  forgotSubtitle:      'Enter the email for your account and we\'ll send you a link to choose a new password.',
  forgotButton:        'Send reset link',
  forgotSent:          'If an account exists for that email, a reset link is on its way. The link expires in 1 hour.',
  backToSignIn:        'Back to sign in',

  resetTitle:          'Choose a new password',
  resetSubtitle:       'Your other devices will be signed out once the new password is saved.',
  resetButton:         'Save new password',
  resetInvalid:        'This reset link is invalid or has expired. Request a new one below.',

  inviteTitle:         'Join your team',
  inviteSubtitle:      'Set your name and password to finish creating your account.',
  inviteJoining:       (org) => `You've been invited to ${org}.`,
  inviteButton:        'Create account',
  inviteInvalid:       'This invitation is invalid, expired, or was revoked. Ask your admin to send a new one.',
  inviteLoading:       'Checking your invitation…',

  verifyTitle:         'Confirm your email',
  verifyChecking:      'Confirming your email…',
  verifySuccess:       'Your email is confirmed. You can now invite teammates.',
  verifyInvalid:       'This confirmation link is invalid or has expired.',
  verifyResend:        'Send a new link',
  verifyResent:        'A new confirmation link is on its way — check your inbox.',
  verifyBanner:        'Confirm your email address to invite teammates and secure your account.',
  verifyBannerAction:  'Resend email',
  continueToDashboard: 'Continue to dashboard',

  newPassword:         'New password',
  confirmPassword:     'Confirm password',
  working:             'Please wait…',
}

export const AUTH_TEAM = {
  heading:             'Team activity',
  teamActivity:        'Team activity',
  teamActivityHint:    'Survey activity by employee',
  subtitle:            'Survey activity by employee',
  surveysBuilt:        'Surveys built',
  responses:           'Responses',
  completion:          'Completion',
  lastActive:          'Last active',
  noActivity:          'No activity yet',
  credentialsOnce:     'Copy these credentials now — the password will not be shown again.',
  passwordResetOnce:   'New password set — copy it now. It will not be shown again.',
  inviteMember:        'Invite member',
  inviteHint:          'They\'ll get an email link to set their own password. Invitations expire in 7 days.',
  inviteSent:          'Invitation sent.',
  pendingInvites:      'Pending invitations',
  resendInvite:        'Resend',
  revokeInvite:        'Revoke',
  inviteResent:        'Invitation re-sent — the previous link no longer works.',
  passwordSelfService: 'Members change their own password from My account, or use “Forgot password?” on the sign-in page.',
}

export const AUTH_PROFILE = {
  myAccount:           'My account',
  myProfile:           'My profile',
  myProfileHint:       'Update how you appear across the platform. Password changes require your current password.',
  displayName:         'Display name',
  username:            'Username',
  email:               'Email',
  emailHint:           'Used to sign in. We\'ll send account notifications to this address when available.',
  profilePhoto:        'Profile photo',
  uploadPhoto:         'Upload photo',
  removePhoto:         'Remove',
  photoHint:           'JPEG, PNG, or WebP · max 512 KB',
  changePassword:      'Change password',
  currentPassword:     'Current password',
  newPassword:         'New password',
  confirmPassword:     'Confirm new password',
  saveProfile:         'Save profile',
  profileSaved:        'Profile updated',
  teamMembers:         'Team members',
  teamHint:            'Invite colleagues and manage roles. Seat usage is tied to your subscription.',
  seatsUsed:           'seats used',
  searchMembers:       'Search by name or username…',
  resetPassword:       'Reset password',
  generatePassword:    'Generate secure password',
  adminResetHint:      'Leave blank to keep the current password, or set a new one for this user.',
  noMembers:           'No team members yet.',
  you:                 'You',
}

export const AUTH_BILLING = {
  heading:             'Billing',
  subtitle:            'Subscription and invoices for your organization',
  plan:                'Current plan',
  status:              'Status',
  seats:               'Seats',
  surveys:             'Surveys',
  periodEnd:           'Renews / trial ends',
  freePrice:           'Free',
  trialBanner:         'You are on a free trial. Paid plans are activated by the vendor once billing is connected.',
  changePlan:            'Change plan',
  changePlanSubtitle:    'Upgrade or downgrade your subscription. Changes take effect immediately.',
  currentPlanBadge:      'Current plan',
  upgradePlan:           'Upgrade',
  downgradePlan:         'Downgrade',
  planChangeSuccess:     'Your plan has been updated.',
  planChangeBlocked:     'This plan change is not available yet.',
  confirmDowngradeTitle: 'Confirm plan downgrade',
  confirmDowngradeBody:  'You will lose access to features included in your current plan. This takes effect immediately.',
  invoices:            'Invoices',
  noInvoices:          'No invoices yet.',
  platformHeading:     'Platform console',
  platformSubtitle:    'Manage organizations, subscriptions, and invoices',
  organizations:       'Organizations',
  selectOrg:           'Select an organization to manage its plan and invoices',
  searchOrgs:          'Search organizations…',
  noOrgs:              'No organizations yet',
  platformEmptyHint:   'Customer organizations will appear here once they sign up.',
  dangerZone:          'Danger zone',
  deleteOrg:           'Delete organization',
  deleteOrgHint:       'Permanently remove this organization, all users, surveys, responses, and billing records. This cannot be undone.',
  deleteOrgConfirmTitle: 'Delete this organization?',
  deleteOrgConfirmBody:  'This permanently deletes the organization and every record inside it — users, surveys, responses, exports, and invoices.',
  deleteOrgTypeName:     'Type the organization name to confirm',
  deleteOrgSuccess:    'Organization deleted.',
  deleteOrgForbidden:  'The platform owner organization cannot be deleted.',
}
